### ISSUE TITLE
Update to current Bootstrap Version

### ISSUE THREAD

**Issue by x-christian-romeni** [m-spyratos/bootstrap-4-grid#1]
Please update to current versions (actually beta already).

Thanks

**Comment by tan-popcorndesign** [comment]
please update

**Comment by m-spyratos** [comment]
The [latest release](https://github.com/m-spyratos/bootstrap-4-grid/releases/tag/2.0.0) uses Bootstrap v4.0.0-beta. Let me know if you step into any issues or have any feedback.
