### ISSUE TITLE
Maybe include bootstrap-reboot.scss?

### ISSUE THREAD

**Issue by diegorodriguesvieira** [m-spyratos/bootstrap-4-grid#2]
I know, this package is only for grid system, but bootstrap reset css is a very good choice.
Let me know what you think...

**Comment by m-spyratos** [comment]
Thanks for the suggestion.

Adding reboot, although it won't harm, it will defeat the purpose of this repo, which is to provide layout assistance to projects that do not want to depend on the full Bootstrap library.

Having said that, you could fork this repo and edit the Gruntfile to add the reboot. You could even grab the reboot.scss file straight from Bootstrap.
