### ISSUE TITLE
SCSS version Not Working

### ISSUE THREAD

**Issue by asmaa3107** [m-spyratos/bootstrap-4-grid#5]
Hi 
I installed your package then **import** your **grid.scss** in my stylesheet
_**but it didn't work**_
**css** worked fine any explain for that.?

**Comment by Meebo-** [comment]
importing the scss without compiling will not work. You have to compile the scss first for it to work.

**Comment by CPritch** [comment]
Guidance for compiling and using SASS can be found here:
[https://sass-lang.com/guide](https://sass-lang.com/guide)
