### ISSUE TITLE
Please consider adding text utilities

### ISSUE THREAD

**Issue by LiadIdan** [m-spyratos/bootstrap-4-grid#6]
It would be great if text utilities will be included.

p.s. position utils will also be a great addition 😁

**Comment by m-spyratos** [comment]
@LiadIdan Thanks for the suggestions!

Added the position utilities in the latest release.
I won't be adding the Text utilities though as I believe it is out of the scope of a Grid system.

Feel free to fork this repo and add it to your own project. It's fairly easy. See my commit of how I added the position utilities:
https://github.com/m-spyratos/bootstrap-4-grid/commit/c4db9d99d7c15b1637d3b405c357fa397a8c281c

**Comment by m-spyratos** [comment]
@LiadIdan Reconsidered and added text utilities like you suggested. Seems that text alignment, wrapping and overflow are pretty common when building layouts. Thanks.
